#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# 2020-08-22 20:14

INFERENCE_INTERVAL = 50  # ms
SMOOTH_INTERVAL = 200  # ms
MIN_PROBABILITY = 0.5
CLIP_DURATION = 1000  # ms

# MFCC
WINDOW_SIZE_MS = 40  # ms
WINDOW_STRIDE_MS = 20  # ms
DCT_COEFFICIENT_COUNT = 10

# !!! dont change
SAMPLE_RATE = 16000
SAMPLES = SAMPLE_RATE * CLIP_DURATION // 1000
FRAMES = (CLIP_DURATION - WINDOW_SIZE_MS) // WINDOW_STRIDE_MS + 1
SMOOTH_SAMPLES = SMOOTH_INTERVAL * SAMPLE_RATE // 1000
CHUNK = SAMPLE_RATE * INFERENCE_INTERVAL // 1000
# !!!

# train
WORDS = ["unknown", "silent", "right"]
