// 2023-04-14 11:49
#ifndef ARM_NEON_H
#define ARM_NEON_H

#include "./reinterp.h"
#include "./vabd.h"
#include "./vadd.h"
#include "./vaddv.h"
#include "./vand.h"
#include "./vcage.h"
#include "./vceq.h"
#include "./vcge.h"
#include "./vcls.h"
#include "./vclz.h"
#include "./vcvt.h"
#include "./veor.h"
#include "./vld.h"
#include "./vmax.h"
#include "./vmaxv.h"
#include "./vmov.h"
#include "./vmul.h"
#include "./vmvn.h"
#include "./vneg.h"
#include "./vorn.h"
#include "./vorr.h"
#include "./vpadd.h"
#include "./vpmax.h"
#include "./vrecp.h"
#include "./vrnd.h"
#include "./vshl.h"
#include "./vshr.h"
#include "./vsqrt.h"
#include "./vtst.h"

#endif  // ARM_NEON_H
